name: modi_python3p6
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - joblib=1.0.1
  - pandas=1.1.5
  - pytz=2021.3
  - threadpoolctl=2.2.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - cairo=1.16.0
  - colorama=0.4.5
  - cycler=0.11.0
  - expat=2.4.8
  - fontconfig=2.14.0
  - gettext=0.19.8.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - graphite2=1.3.13
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.5
  - harfbuzz=2.9.1
  - hdf5=1.12.1
  - icu=68.2
  - jbig=2.1
  - kiwisolver=1.3.1
  - krb5=1.19.3
  - lame=3.100
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.83.1
  - libdeflate=1.10
  - libevent=2.1.10
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libopencv=4.5.3
  - libpq=13.5
  - libprotobuf=3.16.0
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.12
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - opencv=4.5.3
  - pcre=8.45
  - pixman=0.40.0
  - pthread-stubs=0.4
  - py-opencv=4.5.3
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - python-dateutil=2.8.2
  - qt=5.12.9
  - scipy=1.5.3
  - tornado=6.1
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - blas=1.0=mkl
  - ca-certificates=2022.07.19
  - certifi=2021.5.30
  - cudatoolkit=11.7
  - giflib=5.2.1
  - intel-openmp=2020.2
  - jpeg=9e
  - lcms2=2.12
  - libffi=3.3
  - libpng=1.6.37
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - ca-certificates=2022.07.19
  - certifi=2021.5.30
  - giflib=5.2.1
  - intel-openmp=2020.2
  - jpeg=9e
  - lcms2=2.12
  - libffi=3.3
  - libpng=1.6.37
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2020.2=256
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1q
  - pillow=8.3.1
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1q
  - pillow=8.3.1
  - python=3.6.10
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pytorch=1.5.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - torchvision=0.6.0=py36_cu102
  - transformers
  - sentence-transformers
  - tqdm